{% set name = "jaxlie" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jaxlie-{{ version }}.tar.gz
  sha256: 2bf64eb154defd92214253ba1cc6b7ccf43aaaf7da7eb2c8591b66bde205e4f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - typing-extensions >=4.0.0
    - typing_extensions
    - python >=3.8
    - jax >=0.3.18
    - jaxlib >=0.1.67
    - jax-dataclasses >=1.4.4
    - numpy
    - tyro

test:
  imports:
    - jaxlie
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: http://github.com/brentyi/jaxlie
  summary: Matrix Lie groups in JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
