{% set name = "jaxlie" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaxlie-{{ version }}.tar.gz
  sha256: 7465e8faea7dcd5b2a5925aa8e9bcf7e59a3eaa7d6b8dc476dbbeb069079984d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - typing-extensions >=4.0.0
    - typing_extensions >=4.0.0
    - python >={{ python_min }}
    - jax >=0.3.18
    - jaxlib >=0.1.67
    - jax-dataclasses >=1.4.4
    - numpy
    - tyro

test:
  imports:
    - jaxlie
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: http://github.com/brentyi/jaxlie
  summary: Matrix Lie groups in JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
